--- 
- name: Activate a BigIP device license
  connection: local
  hosts: f5-activate
  tasks: 
#    - name: Reset the BIG-IP
#      bigip_config:
#        reset: yes
#        save: True
#        provider: "{{ init_provider }}"
    - name: After reset, configure the expired admin password
      uri: 
        body: "{\"oldPassword\":\"{{ old_bigip_password }}\",\"password\":\"{{ new_bigip_password }}\"}"
        body_format: json
        force_basic_auth: true
        headers: 
          Content-Type: application/json
        method: PATCH
        password: admin
        url: "https://{{ bigip_host }}/mgmt/shared/authz/users/admin"
        user: admin
        validate_certs: false
    - name: Last part of config reset - configure the root password
      bigip_user: 
        full_name: root
        password_credential: "{{ new_bigip_root_password }}"
        provider: "{{ provider }}"
        update_password: always
        username_credential: root
    - name: Activate bigip license
      bigip_device_license: 
        accept_eula: true
        license_key: "{{ bigip_license_key }}"
        license_server: "{{ bigip_license_server }}"
        provider: "{{ provider }}"
      delay: 20
      register: action_result
      retries: 6
      until: "action_result is success"
  vars: 
    init_provider: 
      password: "{{ old_bigip_password }}"
      server: "{{ bigip_host }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: false
    provider: 
      password: "{{ new_bigip_password }}"
      server: "{{ bigip_host }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"

